#!/bin/sh
# prerm for sash
# make sure that accounts using sash will
# at least continue to work after sash is removed...

set -e

if [ "$1" = remove ]; then
    if [ "$(getent passwd | grep  ^sashroot:)" != "" ]; then
        userdel sashroot
    fi
    for sashacct in $(getent passwd | \
        awk -F: '{if ($7 == "/bin/sash") {print $1}}'); do
      chsh -s /bin/bash $sashacct || true
    done
fi

#DEBHELPER#

exit 0
